# Generated by Django 4.1.4 on 2022-12-21 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hello", "0002_student_university_delete_member_student_university"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student", name="admission_year", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="student",
            name="date_of_birth",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="student", name="name", field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="student",
            name="university",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hello.university",
            ),
        ),
        migrations.AlterField(
            model_name="university",
            name="creation_date",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="university",
            name="full_name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="university",
            name="short_name",
            field=models.CharField(max_length=20),
        ),
    ]
