# Generated by Django 4.1.4 on 2022-12-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hello", "0004_alter_university_creation_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="date_of_birth",
            field=models.DateField(max_length=10),
        ),
    ]
