# Generated by Django 4.1.4 on 2022-12-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hello", "0005_alter_student_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="admission_year",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="student", name="date_of_birth", field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="university", name="creation_date", field=models.DateField(),
        ),
    ]
